#' A segmentation object generated from the test data
#'
#' A segmentation object generated by running \code{lean_model} on the test
#' dataset in 'inst/extdata/ChromHMM/SAMPLEDATA_HG18'. The source code to
#' this run is in 'inst/script/test_obj.R'
"test_obj"

#' A a list of segmentation objects generated from the test data
#'
#' A segmentation object generated by running \code{lean_model} on the test
#' dataset in 'inst/extdata/ChromHMM/SAMPLEDATA_HG18' for 3 to 8 states.
#' The source code to this run is in 'inst/script/test_objs.R'
"test_objs"

#' @import chromhmmData
NULL
