name: Build and Push Docker Image

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mahshaaban/segmenter
          dockerfile: inst/extdata/docker/Dockerfile
          tags: latest
